apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../bot-base
- configmap.yaml
commonLabels:
  component: {{COMPONENT}}
patches:
- path: deployment.json
  target:
    group: apps
    kind: Deployment
    name: deployment
    version: v1
patchesStrategicMerge:
- secrets.yaml
nameSuffix: -{{COMPONENT}}
